#
# This configuration file uses placeholders, all $ must be escaped with $$
#

version: 1
formatters:
  simple:
    format: '%(asctime)-9s %(name)s [%(levelname)s] %(message)s'
handlers:
  default:
    formatter: simple
    class: logging.StreamHandler
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [default]
loggers:
  mock:
    level: INFO
